version: '3.9'
services:
  email_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: email-ms
    environment:
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: pecesilloconaji@gmail.com
      EMAIL_PASSWORD: 1002656487
      AMQP_URL: amqps://nqizuvws:Qvlmcfm46yNNWsUVjTWPbbAixvg4Dxo7@fish.rmq.cloudamqp.com/nqizuvws
    ports:
      - 8002:8000
    volumes:
      - .:/app